package com.manank.gymapp;

public class DietData {
    public static String name[] = {
            "Milk",
            "WheatGerm",
            "Bananas",
            "Yogurt",
            "Grapefruits",
            "KetoBread",
            "Coconut",
            "Berries",
            "Smoothie",
            "Toast",
            "Salad",
            "PitaSandwiches",
            "GrilledSandwich",
            "CarnitasBowls",
            "SweetPotato",
            "Banana",
            "YogurtShake",
            "Oatmeal",
            "ProteinBars",
            "PeanutButter",
            "Rice",
            "ChocolateMilk",
            "CottageCheese",
            "EnergyShake",
            "Smoothies",
            "BroccoliCauliflower",
            "CoconutSoup",
            "ParmesanSalad",
            "Sandwich",
            "GrilledSalad"
    };
    public static int image[] = {
            R.mipmap.milk, R.mipmap.wheatgerm, R.mipmap.bananas, R.mipmap.yogurt, R.mipmap.grapefruits,
            R.mipmap.ketobread, R.mipmap.coconut, R.mipmap.berries, R.mipmap.smoothie, R.mipmap.toast,
            R.mipmap.salad, R.mipmap.pitasandwiches, R.mipmap.grilledsandwich, R.mipmap.carnitasbowls, R.mipmap.sweetpotato,
            R.mipmap.banana, R.mipmap.yogurtshake, R.mipmap.oatmeal, R.mipmap.proteinbars, R.mipmap.peanutbutter,
            R.mipmap.rice, R.mipmap.chocolatemilk, R.mipmap.cottagecheese, R.mipmap.energyshake, R.mipmap.smoothies,
            R.mipmap.broccolicauliflower, R.mipmap.coconutsoup, R.mipmap.parmesansalad, R.mipmap.sandwich, R.mipmap.grilledsalad
    };
    public static String desc[] = {
            "Rich in protein and a wealth of important vitamins and minerals, such as selenium and riboflavin",
            "Wheat germ is a component of the wheat kernel that contains a concentrated amount of vitamins and minerals, including manganese, thiamine and selenium.",
            "High in fiber but low in calories, bananas are a great alternative to sugary breakfast cereals to satisfy your sweet tooth first thing in the morning.",
            "Creamy, delicious and satisfying, yogurt makes an excellent addition to a weight loss diet.",
            "Grapefruits are a popular component of many diets and weight loss programs — and for good reason.",
            "Cloud bread, or oopsie bread, is very popular with low-carb and keto dieters. Cloud bread is a protein-rich alternative to regular bread and makes an excellent sandwich base",
            "Coconut is in fact a nutritious superfood that is rich in fiber, vitamins and minerals. Its incredibly healthy, nourishing versatile.",
            "A berry is a small, pulpy, and often edible fruit. Typically, berries are juicy, rounded, brightly colored, sweet, sour or tart, and do not have a stone or pit, although many pips or seeds may be present.",
            "A smoothie is a thick and creamy beverage made from pureed raw fruit, vegetables, and sometimes dairy products, typically using a blender.",
            "Toast is a form of bread that has been browned by exposure to radiant heat. This browning is the result of a Maillard reaction, altering the flavor of the bread and making it firmer so that it is ",
            "We love this take on a classic pasta salad because there are more antioxidant-rich veggies than pasta",
            "This pita pocket is lightened up with the use of low-fat Greek yogurt in place of hefty mayo.",
            "Just smear a layer of hummus onto a toasted slice of Ezekiel whole grain bread, layer on some cucumbers, feta, and tomatoes, and then top with slices",
            "Whip up a batch of this blogger and youll be feasting on high-protein lunches all weeks carnitas, pair it with some satiating beans, crispy lettuce, corn and rice,",
            "A sweet potato is the queen of the slow carbs, meaning your body digests them slowly so they can keep you feeling energized and fuller for longer. ",
            "Bananas are an exercisers BFF. They contain a good amount of glucose, a.k.a. muscle fuel. ",
            "This snack is awesome! Not only is it tasty, but it also incorporates all three macronutrients",
            "The right kind of oatmeal—think steel-cut or old-fashioned, not sugary instant oats—is ideal before a workout. ",
            "The market is flooded with protein bars, and some are better than others. Always check nutrition labels and look closely to make sure theres only one serving in the bar.",
            "Smear on a small amount of peanut butter (about 1 tablespoon) and enjoy.",
            "Rice crackers and peanut butter.",
            "Chocolate milk is sweetened chocolate-flavored milk. It can be made by mixing chocolate syrup with milk. It can be purchased pre-mixed with milk or made at home by blending milk with cocoa ",
            "Cottage cheese is a fresh cheese curd product with a mild flavor. In the past, it was known as curds and whey It is not aged. It is made by draining the cheese, as opposed to pressing it",
            "Despite its health benefits, some people are concerned about its safety. That said, whey protein is safe for most people and a convenient way to increase your protein intake.",
            "Smoothies can make a very healthy breakfast—its all about the ingredients and keeping reasonable portions.",
            "One cup of Broccoli Cheddar soup at Zoup! packs a whopping 290 calories, 20 grams of fat, 60 percent of your daily saturated fat ",
            "Soup is a primarily liquid food, generally served warm or hot (but may be cool or cold), that is made by combining ingredients of meat or vegetables with stock, or water.",
            "Tomato Parmesan Salad. The homemade oil and vinegar dressing is what makes this salad unique. Plus, it features two kinds of lettuce and garden-fresh ",
            "Toast is a form of bread that has been browned by exposure to radiant heat. This browning is the result of a Maillard reaction, altering the flavor of the bread and making it firmer so that it is ",
            "With its commitment to a mission of presenting to its customers delicious and wholesome Salads. Salad Grills has a long term vision of popularizing and"
    };
    public static int calories[] = {
            55,
            60,
            100,
            120,
            40,
            60,
            80,
            40,
            120,
            40,
            330,
            380,
            400,
            200,
            300,
            100,
            80,
            120,
            60,
            60,
            150,
            100,
            100,
            150,
            120,
            200,
            250,
            250,
            320,
            280
    };

}
